[package]
name = "mdown"
version = "0.7.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
reqwest = { version = "0.11.20", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde = "1.0"
serde_json = "1.0"
clap = { version = "4.4.1", features = ["derive"] }
curl = "0.4.44"
zip = "0.6.6"
walkdir = "2.3.2"
indicatif = "0.17.7"
futures = "0.3.28"
colored = "2.0"
rustix = "0.38.19"
lazy_static = "1.4.0"
socket2 = "0.5"
structopt = "0.3"
percent-encoding = "2.1"
rand = "0.8"
webbrowser = "0.8.0"
ctrlc = "3.2.0"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "json"] }

[dependencies.crosscurses]
version = "0.1.0"
features = ["win32"]