[package]
name = "mdown"
version = "0.9.1"
edition = "2021"
authors = ["GrenManSK"]

build = "src/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = { version = "0.22.1", optional = true }
chrono = "0.4.35"
clap = { version = "4.4.18", features = ["derive"] }
crosscurses = { version = "0.1.0", features = ["win32"] }
ctrlc = { version = "3.4.2", optional = true }
eframe = { version = "0.27.2", optional = true }
egui = { version = "0.27.2", optional = true }
egui_extras = { version = "0.27.2", optional = true }
futures = "0.3.30"
if-addrs = { version = "0.12.0", optional = true }
lazy_static = "1.4.0"
parking_lot = "0.12.3"
percent-encoding = { version = "2.3.1", optional = true }
rand = "0.8.5"
regex = "1.10.3"
reqwest = { version = "0.12.1", features = ["json"] }
rusqlite = { version = "0.31.0", features = ["bundled"] }
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
thiserror = "1.0.61"
tokio = { version = "1.35.1", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "json"] }
url = "2.5.0"
uuid = "1.7.0"
walkdir = "2.4.0"
webbrowser = { version = "1", optional = true }
zip = "0.6.6"


[build-dependencies]
winres = "0.1.12"

[dev-dependencies]
h2 = "0.4.4"

[features]
full = ["web", "gui", "server"]
web = ["webbrowser", "base64", "ctrlc", "percent-encoding"]
server = ["webbrowser", "if-addrs", "percent-encoding", "ctrlc"]
gui = ["eframe", "egui", "egui_extras"]
